import Head from 'next/head';
import { Footer } from '../components/footer';
import { Header } from '../components/header';


export default function Home() {
  return (
    <div className='text-white'>
      <Head>
        <title>Tiny Colony MVP</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='hidden lg:block'>
        <Header />
        <main>
        </main>
        <Footer />
      </div>
    </div>
  );
}
